[[headers]]
    for = "/*"
    [headers.values]
        Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
        X-Content-Type-Options = "nosniff"
        X-Frame-Options = "SAMEORIGIN"
        X-XSS-Protection = "1; mode=block"

[[headers]]
    for = "/assets/*"
    [headers.values]
        Cache-Control = "max-age=604800"
